# Generated by Django 5.1.2 on 2024-11-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('ID_venta', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('Precio', models.PositiveBigIntegerField()),
                ('Fecha', models.DateField()),
                ('ID_Producto', models.PositiveBigIntegerField()),
                ('ID_Cliente', models.PositiveBigIntegerField()),
                ('ID_Empleado', models.PositiveBigIntegerField()),
                ('ID_Sucursal', models.PositiveBigIntegerField()),
            ],
        ),
    ]
