# Generated by Django 5.1.2 on 2024-11-28 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('ID_empleado', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Puesto', models.CharField(max_length=50)),
                ('Sueldo', models.PositiveBigIntegerField()),
                ('Telefono', models.PositiveBigIntegerField()),
                ('Fecha_nac', models.DateField()),
                ('Genero', models.CharField(max_length=50)),
            ],
        ),
    ]
